# Generated by Django 6.0.6 on 2026-07-05 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Уровень')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний ответ')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.card', verbose_name='Карточка')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progresses', to='courses.enrollment', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Прогресс по карточке',
                'verbose_name_plural': 'Прогресс по карточкам',
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'card'), name='unique_enrollment_card')],
            },
        ),
    ]
