# Generated by Django 6.0.6 on 2026-07-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_cardprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='seconds_per_word',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='seconds_per_word',
        ),
    ]
