# Generated by Django 6.0.6 on 2026-07-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_seconds_per_word_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cardprogress',
            name='unique_enrollment_card',
        ),
        migrations.AddField(
            model_name='cardprogress',
            name='direction',
            field=models.CharField(choices=[('word_to_translation', 'Слово → перевод'), ('translation_to_word', 'Перевод → слово')], default='word_to_translation', max_length=20, verbose_name='Направление'),
        ),
        migrations.AddConstraint(
            model_name='cardprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'card', 'direction'), name='unique_enrollment_card_direction'),
        ),
    ]
