# Generated by Django 6.0.6 on 2026-07-05 20:34

from django.db import migrations


def create_reverse_direction(apps, schema_editor):
    """Для каждого существующего прогресса (слово → перевод) создаёт
    второе направление (перевод → слово) с уровнем 0."""
    CardProgress = apps.get_model('courses', 'CardProgress')
    CardProgress.objects.bulk_create(
        (
            CardProgress(
                enrollment_id=progress.enrollment_id,
                card_id=progress.card_id,
                direction='translation_to_word',
                level=0,
            )
            for progress in CardProgress.objects
            .filter(direction='word_to_translation')
            .iterator()
        ),
        ignore_conflicts=True,
    )


def remove_reverse_direction(apps, schema_editor):
    CardProgress = apps.get_model('courses', 'CardProgress')
    CardProgress.objects.filter(direction='translation_to_word').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_cardprogress_unique_enrollment_card_and_more'),
    ]

    operations = [
        migrations.RunPython(create_reverse_direction, remove_reverse_direction),
    ]
