# Generated by Django 6.0.6 on 2026-07-05 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_backfill_reverse_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprogress',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Уровень'),
        ),
    ]
