# Generated by Django 6.0.6 on 2026-07-05 21:16

from django.db import migrations

NEW_MAX_LEVEL = 3


def clamp_levels(apps, schema_editor):
    """Максимальный уровень снижен с 5 до 3 — уровни выше приводим к 3."""
    CardProgress = apps.get_model('courses', 'CardProgress')
    CardProgress.objects.filter(level__gt=NEW_MAX_LEVEL).update(level=NEW_MAX_LEVEL)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_cardprogress_level'),
    ]

    operations = [
        migrations.RunPython(clamp_levels, migrations.RunPython.noop),
    ]
