# Generated by Django 6.0.6 on 2026-07-19 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_clamp_levels_to_new_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='answers_correct',
            field=models.PositiveIntegerField(default=0, verbose_name='Верных ответов'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='answers_wrong',
            field=models.PositiveIntegerField(default=0, verbose_name='Неверных ответов'),
        ),
        migrations.AlterField(
            model_name='cardprogress',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Уровень'),
        ),
    ]
