# Generated by Django 6.0.6 on 2026-07-20 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_clamp_levels_to_new_max'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Успешных прохождений'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='ever_completed',
            field=models.BooleanField(default=False, verbose_name='Пройден хотя бы раз'),
        ),
        migrations.CreateModel(
            name='AnswerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='Верный ответ')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Момент ответа')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to='courses.enrollment', verbose_name='Запись')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Ответ (лог)',
                'verbose_name_plural': 'Ответы (лог)',
                'indexes': [models.Index(fields=['student', 'answered_at'], name='courses_ans_student_a9746d_idx')],
            },
        ),
    ]
