# Generated by Django 6.0.6 on 2026-07-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_backfill_completed_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='best_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Лучший результат, %'),
        ),
    ]
