# Generated by Django 6.0.6 on 2026-07-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_enrollment_best_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprogress',
            name='current_streak',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Верных подряд'),
        ),
    ]
